[#1466] Fix autocomplete for aliased subcommands
remkop/picocli pull request #1467
Opened 2021-11-17 10:54 UTC by rsenden

This PR fixes #1466

2021-11-17 12:47 UTC, remkop commented
This is great, thank you!
Can you add a test for this, or modify one of the existing tests?

2021-11-17 15:05 UTC, rsenden commented
I just added aliases to the existing AutoComplete tests, and updated the expected outputs. The only thing that I'm not sure about is why in AutoCompleteTest#testComplete() I need to repeat each alias three times. Any idea?

2021-11-18 07:25 UTC, remkop commented
> The only thing that I'm not sure about is why in AutoCompleteTest#testComplete() I need to repeat each alias three times. Any idea?

I will have to take a look in the debugger to see what is going on. It may take some time before I can get to this.

2021-11-24 09:07 UTC, remkop commented
I finally had some time to take a look at this.
It appears that the `AutoComplete#filterAndTrimMatchingPrefix` method does not filter out duplicates, even though it should. This can be fixed by modifying the first line of this method to use a `Set` instead of a `List`:

```java
    private static void filterAndTrimMatchingPrefix(String prefix, List<CharSequence> candidates) {
        Set<CharSequence> replace = new HashSet<CharSequence>();
        ...
```

The expectations in `testComplete` can then be changed to also have only one occurrence of each of the subcommand aliases, which makes much more sense.

Can you change the PR accordingly?

2021-11-24 09:13 UTC, remkop requested changes
I also found some minor things with variables used in the test result templates that should be preserved. Can you take a look?

2021-11-24 09:13 UTC, remkop commented on src/test/resources/picocompletion-demo-help_completion.bash
> +# generated by [picocli](http://picocli.info/) version 4.6.3-SNAPSHOT.
Please leave the `%1$s` variable, it will be replaced by the latest version in the test.

2021-11-24 09:13 UTC, remkop commented on src/test/resources/picocompletion-demo-help_completion.bash
> +  local timeUnit_option_args="NANOSECONDS MICROSECONDS MILLISECONDS SECONDS MINUTES HOURS DAYS" # --timeUnit values
Please leave the `%2$s` variable, it will be replaced by the supported TimeUnit constants for the version of Java that is running the test.

2021-11-24 09:13 UTC, remkop commented on src/test/resources/picocompletion-demo_completion.bash
> +# generated by [picocli](http://picocli.info/) version 4.6.3-SNAPSHOT.
Please leave the `%1$s` variable, it will be replaced by the latest version in the test.

2021-11-24 09:13 UTC, remkop commented on src/test/resources/picocompletion-demo_completion.bash
> +  local timeUnit_option_args="NANOSECONDS MICROSECONDS MILLISECONDS SECONDS MINUTES HOURS DAYS" # --timeUnit values
Please leave the `%2$s` variable, it will be replaced by the supported TimeUnit constants for the version of Java that is running the test.

2021-11-24 11:43 UTC, rsenden commented
PR has been updated with all requested changes

2021-11-24 12:00 UTC, merged

2021-11-24 12:02 UTC, remkop commented
Merged. 
Thank you for the contribution!

I will update the release notes when I get to my PC.