[#1380] Fix for requiredOptionMarker displayed on ArgGroup
remkop/picocli pull request #1505
Opened 2021-12-08 07:14 UTC by ahmede41

fix for Issue#1380

https://github.com/remkop/picocli/issues/1380

2021-12-08 08:05 UTC, remkop commented on .gitignore
> +docs/
This is not correct; the `docs/` folder should not be in `.gitignore`: the https://picocli.info website is mapped to that directory.

2021-12-09 03:06 UTC, remkop commented
(I had a longer overall comment but I can't see it now so let me post it again.)

Thank you for this PR!

Looking bacl at the [commit](https://github.com/remkop/picocli/commit/79ec413204b6db995f77414d2c4360480a6fdc5e) for issue #871 that made options in exclusive groups required, it is clear that this solution resulted in a loss of information: it became impossible to determine whether an option was originally marked as `required = true` or not. Which is the direct cause of #1380.

I like the approach of this PR to add a field to store the original value of `required`.

I also like the fact that the PR adds several tests, nice! (Also thanks for the test for #1420, that will be useful when working on that ticket.)
I did have some feedback on the tests to make them smaller and more concise, can you take a look?

Also I noticed that this PR modifies several html files in the `docs/` folder, can those changes be excluded from this PR?

I like the approach of this PR, I think it is the correct way to go.
One small thing is the naming of the newly added field.
Can you take a look at my feedback on that?

2021-12-10 05:53 UTC, ahmede41 commented
> (I had a longer overall comment but I can't see it now so let me post it again.)
> 
> Thank you for this PR!
> 
> Looking back at the [commit](https://github.com/remkop/picocli/commit/79ec413204b6db995f77414d2c4360480a6fdc5e) for issue #871 that made options in exclusive groups required, it is clear that this solution resulted in a loss of information: it became impossible to determine whether an option was originally marked as `required = true` or not. Which is the direct cause of #1380.
> 
> I like the approach of this PR to add a field to store the original value of `required`.
> 
> I also like the fact that the PR adds several tests, nice! (Also thanks for the test for #1420, that will be useful when working on that ticket.) I did have some feedback on the tests to make them smaller and more concise, can you take a look?
> 
> Also I noticed that this PR modifies several html files in the `docs/` folder, can those changes be excluded from this PR?
> 
> I like the approach of this PR, I think it is the correct way to go. One small thing is the naming of the newly added field. Can you take a look at my feedback on that?

@remkop somehow I don't see any comments/feedback on code, Can you check?

2021-12-10 06:10 UTC, remkop requested changes
> @remkop somehow I don't see any comments/feedback on code, Can you check?

I think I lost my comment and then did not press the "Submit review" button so my feedback has been pending all the time... sorry about that.

Hopefully the individual comments will become visible when I click "Submit review" on this comment. Summary of the main items:
* I did have some feedback on the tests to make them smaller and more concise, can you take a look?
* I noticed that this PR modifies several html files in the docs/ folder, can those changes be excluded from this PR?
* I like the approach of this PR, I think it is the correct way to go. One small thing is the naming of the newly added field. Can you take a look at my feedback on that?

2021-12-17 05:54 UTC, ahmede41 commented on src/main/java/picocli/CommandLine.java
> +            public boolean optionIsNotRequired(){
Updated

2021-12-17 05:54 UTC, ahmede41 commented on src/main/java/picocli/CommandLine.java
> +             * @see Option#optionIsNotRequired() */
Updated

2021-12-17 05:54 UTC, ahmede41 commented on src/main/java/picocli/CommandLine.java
> +             * If this argument is part of a {@linkplain ArgGroup group}, this method returns whether this argument is required <em>within the group</em> (so it is not necessarily a required argument
Updated

2021-12-17 05:54 UTC, ahmede41 commented on src/main/java/picocli/CommandLine.java
> +            /** Returns whether this is a required option or positional parameter without a default value.
Updated

2021-12-17 05:54 UTC, ahmede41 commented on src/main/java/picocli/CommandLine.java
> +            private boolean optionIsNotRequired;
Updated

2021-12-17 05:55 UTC, ahmede41 commented on picocli-annotation-processing-tests/src/test/java/picocli/Issue1380Test.java
> +        public boolean getVerbose() {
removed

2021-12-17 05:55 UTC, ahmede41 commented on picocli-annotation-processing-tests/src/test/java/picocli/Issue1380Test.java
> +        public boolean getSilent() {
that was needed for my course work, removed

2021-12-17 05:55 UTC, ahmede41 commented on qaplug_result.html
> +</html>
This was part of my course work, I removed the file.

2021-12-17 06:08 UTC, ahmede41 reviewed
Updated as requested

2021-12-17 06:09 UTC, ahmede41 commented
updated Can you check if all good?

2021-12-17 18:59 UTC, ahmede41 commented
Docs folder changes were all whitespaces something from my bad IDE, that is why I had on .gitignore initially

2021-12-18 03:17 UTC, remkop requested changes
Thank you for the changes.
I think we are almost there.

One thing: this pull request still contains many modifications to HTML files in the `docs/` folder. 
I don't want to modify those files.
Can you revert the changes to the HTML files in the `docs/` folder?

2021-12-18 03:17 UTC, remkop commented on src/main/java/picocli/CommandLine.java
> +            private boolean optionIsNotRequired;
Great, thank you!

2021-12-18 03:17 UTC, remkop commented on src/main/java/picocli/CommandLine.java
> +            /** Returns whether this is a required option or positional parameter without a default value.
How about this instead:

"Returns the original value of the option's <code>required</code> attribute, regardless of whether the option is used in an exclusive group or not."

2021-12-18 10:25 UTC, ahmede41 commented
> Thank you for the changes. I think we are almost there.
> 
> One thing: this pull request still contains many modifications to HTML files in the `docs/` folder. I don't want to modify those files. Can you revert the changes to the HTML files in the `docs/` folder?

I reverted the docs/ files

2021-12-18 10:48 UTC, ahmede41 commented on src/main/java/picocli/CommandLine.java
> +            /** Returns whether this is a required option or positional parameter without a default value.
Updated

2021-12-18 13:33 UTC, remkop approved these changes
Great, thank you for making the changes.
This looks ready to merge now.

I just need to decide on whether I will do a 4.6.3 release first or not.
I am a bit preoccupied with the Log4j issue at the moment, so this may take some time.

Thank you again for the contribution!

2021-12-20 03:09 UTC, remkop commented
I am seeing the following test failures. Can you take a look?

```
> Task :picocli-annotation-processing-tests:test

picocli.Issue1380Test > testingWithExclusiveTrue FAILED
    org.junit.ComparisonFailure at Issue1380Test.java:68

picocli.Issue1380Test > testingWithExclusiveFalse FAILED
    org.junit.ComparisonFailure at Issue1380Test.java:86
```

2021-12-20 18:04 UTC, ahmede41 commented
> I am seeing the following test failures. Can you take a look?
> 
> ```
> > Task :picocli-annotation-processing-tests:test
> 
> picocli.Issue1380Test > testingWithExclusiveTrue FAILED
>     org.junit.ComparisonFailure at Issue1380Test.java:68
> 
> picocli.Issue1380Test > testingWithExclusiveFalse FAILED
>     org.junit.ComparisonFailure at Issue1380Test.java:86
> ```

I just rechecked the test and did a clean rebuild (`./gradlew clean build`) and no failure seen here


```
Issue1380Test: 2 total, 2 passed
Collapse | Expand
240 mspicocli.Issue1380Test
234 mspassedtestingWithExclusiveTrue
6 mspassedtestingWithExclusiveFalse

```
```
BUILD SUCCESSFUL in 3m 13s
98 actionable tasks: 98 executed
```

2022-02-10 09:18 UTC, remkop approved these changes

2022-02-10 09:53 UTC, merged

2022-02-10 11:29 UTC, remkop commented
Merged. Thank you for the contribution and for your patience!