Review, please -- "simple" example for command-line program
remkop/picocli pull request #1542
Opened 2022-01-03 17:02 UTC by binkley

For issue #1540

This PR is more for review & guidance than for merging (though it is mergeable best I can tell).
I'm looking to see if I'm heading in the right direction before I go too far along.

Things I'd like to understand/address include:
- How should I test this code?
- Is it OK to create an executable uberjar?  (I'm using this for manual command-line testing)
- Is there a better way to detect "isatty"?
- Did I pick the right directory and/or package for this work?

2022-01-03 17:14 UTC, binkley commented
The initial commits are all code.

Before I write up separate documentation, I'd like working code to back up those docs.

2022-01-08 00:41 UTC, remkop commented
Hi, sorry for the late response. I have been traveling with family. It may take me some time to get to this.

2022-02-08 06:35 UTC, remkop requested changes
Overall, this approach is not one I would take.

This approach uses picocli as an entry point, from which a JLine (or JLine-like) REPL is started, after which the `YourProcessing` class somehow needs to deal with the user input.

One problem of this approach is that it is not clear is how the application would tokenize the user input: given an input string of `mycommand --option --option2=value a b x,y,z` we want to break this up into `mycommand`, `--option`, `--option2=value`, `a`, `b`, and `x,y,z`, so we can invoke `CommandLine.execute(args)` with these tokens. JLine3 provides this functionality, and much more, out of the box. IMO it pays to spend the time to become familiar with the functionality that JLine3 offers rather than re-implementing this functionality ourselves.

The example in the https://github.com/remkop/picocli/blob/master/picocli-shell-jline3/README.md uses the JLine3 API extensively, and is more in line with what I would recommend to application authors. 

The Example in the README shows how to wire together picocli commands with JLine3.
Once that wiring is in place, your REPL application can support any number of commands, that can simply use the picocli API (`Runnable` or `Callable` classes with `@Option` or `@Parameters`-annotated fields) to define these commands.

There is a learning curve to this, but on the other hand it allows for application code to work at a much higher level of abstraction.

2022-02-08 06:35 UTC, remkop commented on picocli-shell-jline3/src/main/java/picocli/tool/jline3/ExampleTool.java
> +        try (final BufferedReader lineReader = lineReader()) {
This method seems to be a rudimentary re-implementation of JLine functionality.
I don't think we should suggest to users that they do this.
My recommendation to users would be to familiarize themselves with what JLine offers and use that instead.

2022-02-08 06:35 UTC, remkop commented on picocli-shell-jline3/src/main/java/picocli/tool/jline3/ExampleTool.java
> +     * @todo Newer versions of Java permit defining this as a lambda
Do we need this TODO?

2022-02-08 06:35 UTC, remkop commented on picocli-shell-jline3/src/main/java/picocli/tool/jline3/ExampleTool.java
> +                    // Handling user banging on <kbd>Ctrl-C</kbd>
Do we want to catch these exceptions here?
My preference would be to let this method throw these exceptions and handle them in the place where this method is called.

2022-02-08 06:35 UTC, remkop commented on picocli-shell-jline3/src/main/java/picocli/tool/jline3/ExampleTool.java
> +            // TODO: It is challenging in Java to return _both_ a status code
If processing the exception is challenging them perhaps we should not catch it here, or perhaps we should wrap it in a custom exception and re-throw it .

2022-02-08 06:35 UTC, remkop commented on picocli-shell-jline3/src/main/java/picocli/tool/jline3/ExampleTool.java
> +    //  the command line, output results, and to let caller handle exceptions
Can we remove this TODO?

2022-06-27 08:23 UTC, closed without merging