Optimize incremental builds and local build cache usage
remkop/picocli pull request #1807
Opened 2022-09-09 12:57 UTC by jean-andre-gauthier

- Optimize incremental builds
  - Replace copyJavadocDocFiles workaround by javadoc sourcepath
  - Specify output dir in generateManpageAsciiDoc task
  - Specify output file in generateVersionTxt task
- Optimize local build cache usage
  - Add normalization for manifest.mf to ignore Bnd-LastModified attribute
  - Add normalization for version.txt in 'picocli-examplesto ignoreBuildtime` property

2022-09-09 13:05 UTC, jean-andre-gauthier commented
@runningcode FYI

2022-09-09 15:26 UTC, runningcode approved these changes
looks good!

2022-09-09 15:26 UTC, runningcode commented on gradle.properties
> +org.gradle.caching = false
don't commit this.

2022-09-11 00:45 UTC, remkop requested changes
Thank you for this pull request!

Overall, looks good.
I see @runningcode already added a comment on the change to `gradle.properties` about not disabling gradle caching.
Can you make that change, or otherwise argue the case of why this change should be included?

2022-09-12 06:45 UTC, jean-andre-gauthier commented
Thanks very much for the review, I've removed `gradle.properties` as shouldn't have been committed in the first place

2022-09-12 08:32 UTC, remkop approved these changes

2022-09-12 09:05 UTC, merged

2022-09-12 09:21 UTC, remkop commented
Merged. Thank you for the pull request!